# Generated by Django 2.0.4 on 2018-04-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='2017-01-01', upload_to='records'),
            preserve_default=False,
        ),
    ]
